using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using static Sumirin_Beta__Falling_Apart__Slab.Properties.Settings;

namespace Sumirin_Beta__Falling_Apart__Slab.Screen
{
    public partial class FrmMain
    {
        // define
        private readonly int _span = Default.Span;

        // Initialize items
        private void InitItems()
        {
            InitPnlAs();
            InitPnlIs();
            InitLblTits();
            InitChkAs();
            InitNudWs();
            InitNudHs();
            InitNudDs();
            InitNudTits();
            InitNudGs();
        }

        private List<Panel> _pnlAs;
        // Initialize list pnlA
        private void InitPnlAs() => _pnlAs = new List<Panel>
            {
                pnlASH1,
                pnlASH2,
                pnlASH3,
                pnlASH4,
                pnlASH5,
                pnlASH6,
                pnlASH7,
                pnlASH8,
                pnlASH9,
                pnlASH10,
                pnlASV1,
                pnlASV2,
                pnlASV3,
                pnlASV4,
                pnlASV5,
                pnlASV6,
                pnlASV7,
                pnlASV8,
                pnlASV9,
                pnlASV10,
                pnlARH1,
                pnlARH2,
                pnlARH3,
                pnlARH4,
                pnlARH5,
                pnlARH6,
                pnlARV1,
                pnlARV2,
                pnlARV3,
                pnlARV4,
                pnlARV5,
                pnlARV6
            };

        private List<Panel> _pnlIs;
        // Initialize list pnlI
        private void InitPnlIs() => _pnlIs = new List<Panel>
            {
                pnlISH1,
                pnlISH2,
                pnlISH3,
                pnlISH4,
                pnlISH5,
                pnlISH6,
                pnlISH7,
                pnlISH8,
                pnlISH9,
                pnlISH10,
                pnlISV1,
                pnlISV2,
                pnlISV3,
                pnlISV4,
                pnlISV5,
                pnlISV6,
                pnlISV7,
                pnlISV8,
                pnlISV9,
                pnlISV10,
                pnlIRH1,
                pnlIRH2,
                pnlIRH3,
                pnlIRH4,
                pnlIRH5,
                pnlIRH6,
                pnlIRV1,
                pnlIRV2,
                pnlIRV3,
                pnlIRV4,
                pnlIRV5,
                pnlIRV6
            };

        private List<Label> _lblTits;
        // Initialize list lblTit
        private void InitLblTits() => _lblTits = new List<Label>
            {
                lblWSH1,
                lblWSH2,
                lblWSH3,
                lblWSH4,
                lblWSH5,
                lblWSH6,
                lblWSH7,
                lblWSH8,
                lblWSH9,
                lblWSH10,
                lblWSV1,
                lblWSV2,
                lblWSV3,
                lblWSV4,
                lblWSV5,
                lblWSV6,
                lblWSV7,
                lblWSV8,
                lblWSV9,
                lblWSV10,
                lblWRH1,
                lblWRH2,
                lblWRH3,
                lblWRH4,
                lblWRH5,
                lblWRH6,
                lblWRV1,
                lblWRV2,
                lblWRV3,
                lblWRV4,
                lblWRV5,
                lblWRV6,
                lblHSH1,
                lblHSH2,
                lblHSH3,
                lblHSH4,
                lblHSH5,
                lblHSH6,
                lblHSH7,
                lblHSH8,
                lblHSH9,
                lblHSH10,
                lblHSV1,
                lblHSV2,
                lblHSV3,
                lblHSV4,
                lblHSV5,
                lblHSV6,
                lblHSV7,
                lblHSV8,
                lblHSV9,
                lblHSV10,
                lblHRH1,
                lblHRH2,
                lblHRH3,
                lblHRH4,
                lblHRH5,
                lblHRH6,
                lblHRV1,
                lblHRV2,
                lblHRV3,
                lblHRV4,
                lblHRV5,
                lblHRV6,
                lblDRH1,
                lblDRH2,
                lblDRH3,
                lblDRH4,
                lblDRH5,
                lblDRH6,
                lblDRV1,
                lblDRV2,
                lblDRV3,
                lblDRV4,
                lblDRV5,
                lblDRV6
            };

        private List<CheckBox> _chkAs;
        // Initialize list chkA
        private void InitChkAs() => _chkAs = new List<CheckBox>
            {
                chkASH1,
                chkASH2,
                chkASH3,
                chkASH4,
                chkASH5,
                chkASH6,
                chkASH7,
                chkASH8,
                chkASH9,
                chkASH10,
                chkASV1,
                chkASV2,
                chkASV3,
                chkASV4,
                chkASV5,
                chkASV6,
                chkASV7,
                chkASV8,
                chkASV9,
                chkASV10,
                chkARH1,
                chkARH2,
                chkARH3,
                chkARH4,
                chkARH5,
                chkARH6,
                chkARV1,
                chkARV2,
                chkARV3,
                chkARV4,
                chkARV5,
                chkARV6
            };

        private List<NumericUpDown> _nudWs;
        // Initialize list nudW
        private void InitNudWs() => _nudWs = new List<NumericUpDown>
            {
                nudWSH1,
                nudWSH2,
                nudWSH3,
                nudWSH4,
                nudWSH5,
                nudWSH6,
                nudWSH7,
                nudWSH8,
                nudWSH9,
                nudWSH10,
                nudWSV1,
                nudWSV2,
                nudWSV3,
                nudWSV4,
                nudWSV5,
                nudWSV6,
                nudWSV7,
                nudWSV8,
                nudWSV9,
                nudWSV10,
                nudWRH1,
                nudWRH2,
                nudWRH3,
                nudWRH4,
                nudWRH5,
                nudWRH6,
                nudWRV1,
                nudWRV2,
                nudWRV3,
                nudWRV4,
                nudWRV5,
                nudWRV6
            };

        private List<NumericUpDown> _nudHs;
        // Initialize list nudH
        private void InitNudHs() => _nudHs = new List<NumericUpDown>
            {
                nudHSH1,
                nudHSH2,
                nudHSH3,
                nudHSH4,
                nudHSH5,
                nudHSH6,
                nudHSH7,
                nudHSH8,
                nudHSH9,
                nudHSH10,
                nudHSV1,
                nudHSV2,
                nudHSV3,
                nudHSV4,
                nudHSV5,
                nudHSV6,
                nudHSV7,
                nudHSV8,
                nudHSV9,
                nudHSV10,
                nudHRH1,
                nudHRH2,
                nudHRH3,
                nudHRH4,
                nudHRH5,
                nudHRH6,
                nudHRV1,
                nudHRV2,
                nudHRV3,
                nudHRV4,
                nudHRV5,
                nudHRV6
            };

        private List<NumericUpDown> _nudDs;
        // Initialize list nudD
        private void InitNudDs() => _nudDs = new List<NumericUpDown>
            {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                nudDRH1,
                nudDRH2,
                nudDRH3,
                nudDRH4,
                nudDRH5,
                nudDRH6,
                nudDRV1,
                nudDRV2,
                nudDRV3,
                nudDRV4,
                nudDRV5,
                nudDRV6
            };

        private List<NumericUpDown> _nudTits;
        // Initialize list nudTit
        private void InitNudTits() => _nudTits = new List<NumericUpDown>
            {
                nudWSH1,
                nudWSH2,
                nudWSH3,
                nudWSH4,
                nudWSH5,
                nudWSH6,
                nudWSH7,
                nudWSH8,
                nudWSH9,
                nudWSH10,
                nudWSV1,
                nudWSV2,
                nudWSV3,
                nudWSV4,
                nudWSV5,
                nudWSV6,
                nudWSV7,
                nudWSV8,
                nudWSV9,
                nudWSV10,
                nudWRH1,
                nudWRH2,
                nudWRH3,
                nudWRH4,
                nudWRH5,
                nudWRH6,
                nudWRV1,
                nudWRV2,
                nudWRV3,
                nudWRV4,
                nudWRV5,
                nudWRV6,
                nudHSH1,
                nudHSH2,
                nudHSH3,
                nudHSH4,
                nudHSH5,
                nudHSH6,
                nudHSH7,
                nudHSH8,
                nudHSH9,
                nudHSH10,
                nudHSV1,
                nudHSV2,
                nudHSV3,
                nudHSV4,
                nudHSV5,
                nudHSV6,
                nudHSV7,
                nudHSV8,
                nudHSV9,
                nudHSV10,
                nudHRH1,
                nudHRH2,
                nudHRH3,
                nudHRH4,
                nudHRH5,
                nudHRH6,
                nudHRV1,
                nudHRV2,
                nudHRV3,
                nudHRV4,
                nudHRV5,
                nudHRV6,
                nudDRH1,
                nudDRH2,
                nudDRH3,
                nudDRH4,
                nudDRH5,
                nudDRH6,
                nudDRV1,
                nudDRV2,
                nudDRV3,
                nudDRV4,
                nudDRV5,
                nudDRV6
            };

        private List<NumericUpDown> _nudGs;
        // Initialize list nudG
        private void InitNudGs() => _nudGs = new List<NumericUpDown>
            {
                nudWSH1,
                nudWSH2,
                nudWSH3,
                nudWSH4,
                nudWSH5,
                nudWSH6,
                nudWSH7,
                nudWSH8,
                nudWSH9,
                nudWSH10,
                nudWSV1,
                nudWSV2,
                nudWSV3,
                nudWSV4,
                nudWSV5,
                nudWSV6,
                nudWSV7,
                nudWSV8,
                nudWSV9,
                nudWSV10,
                nudWRH1,
                nudWRH2,
                nudWRH3,
                nudWRH4,
                nudWRH5,
                nudWRH6,
                nudWRV1,
                nudWRV2,
                nudWRV3,
                nudWRV4,
                nudWRV5,
                nudWRV6,
                nudHSH1,
                nudHSH2,
                nudHSH3,
                nudHSH4,
                nudHSH5,
                nudHSH6,
                nudHSH7,
                nudHSH8,
                nudHSH9,
                nudHSH10,
                nudHSV1,
                nudHSV2,
                nudHSV3,
                nudHSV4,
                nudHSV5,
                nudHSV6,
                nudHSV7,
                nudHSV8,
                nudHSV9,
                nudHSV10,
                nudHRH1,
                nudHRH2,
                nudHRH3,
                nudHRH4,
                nudHRH5,
                nudHRH6,
                nudHRV1,
                nudHRV2,
                nudHRV3,
                nudHRV4,
                nudHRV5,
                nudHRV6
            };
    }
}
