//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sumirin_Beta__Falling_Apart__Slab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sumirin_Beta__Falling_Apart__Slab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumirin Beta (Falling Apart) Slab.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スラブ住本林業（ベタ・バラバラ）.
        /// </summary>
        internal static string app_true_name {
            get {
                return ResourceManager.GetString("app_true_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.12.14.
        /// </summary>
        internal static string app_ver {
            get {
                return ResourceManager.GetString("app_ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAN.
        /// </summary>
        internal static string co_name {
            get {
                return ResourceManager.GetString("co_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WUFOIOOCueODqeODluS9j+acrOael+alre+8iOODmeOCv+ODu+ODkOODqeODkOODqe+8iQ==.
        /// </summary>
        internal static string key_ser {
            get {
                return ResourceManager.GetString("key_ser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/Tynab/Tynab/main/app/Sumirin%20Beta%20(Falling%20Apart)%20Slab.
        /// </summary>
        internal static string link_app {
            get {
                return ResourceManager.GetString("link_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to google.com.
        /// </summary>
        internal static string link_base {
            get {
                return ResourceManager.GetString("link_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/Tynab/Tynab/main/ver/Sumirin%20Beta%20(Falling%20Apart)%20Slab.
        /// </summary>
        internal static string link_ver {
            get {
                return ResourceManager.GetString("link_ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pOff {
            get {
                object obj = ResourceManager.GetObject("pOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sBack {
            get {
                return ResourceManager.GetStream("sBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sChange {
            get {
                return ResourceManager.GetStream("sChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sHover {
            get {
                return ResourceManager.GetStream("sHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sNext {
            get {
                return ResourceManager.GetStream("sNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sPress {
            get {
                return ResourceManager.GetStream("sPress", resourceCulture);
            }
        }
    }
}
